# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - questionoftheday2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_85647ab215b94f8ea8d249f0d2c4be36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cd11eb4bf4f140bb8055b8539c774df6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85647ab215b94f8ea8d249f0d2c4be36 }}/qotd:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'questionoftheday2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fe6414f5e77d44e782bbfdc04ba821e6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85647ab215b94f8ea8d249f0d2c4be36 }}/qotd:${{ github.sha }}'